import type { Gym } from "./types";

export const DEMO_GYMS: Gym[] = [
  {
    id: "demo-cbd",
    name: "Kenya Fitness Hub",
    address: "Kenyatta Avenue, Nairobi CBD",
    location: { lat: -1.2833, lng: 36.8219 },
    rating: 4.6,
    userRatingCount: 214,
    priceLevel: "PRICE_LEVEL_MODERATE",
    openNow: true,
    types: ["gym", "fitness_center"],
    photoName: null,
    googleMapsUri: "https://www.google.com/maps/search/?api=1&query=gym%20Nairobi%20CBD",
    phone: null,
    website: null,
    weekdayHours: ["Monday: 5:00 AM – 10:00 PM"],
    reviews: [{ text: "Great weights floor and morning HIIT classes.", rating: 5 }],
    editorialSummary: "Central Nairobi gym with strength equipment and group classes.",
    distanceKm: null,
    score: 0,
    labels: [],
    isDemo: true,
  },
  {
    id: "demo-westlands",
    name: "Westlands Strength Lab",
    address: "Waiyaki Way, Westlands, Nairobi",
    location: { lat: -1.2675, lng: 36.806 },
    rating: 4.8,
    userRatingCount: 162,
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    openNow: true,
    types: ["gym"],
    photoName: null,
    googleMapsUri: "https://www.google.com/maps/search/?api=1&query=gym%20Westlands%20Nairobi",
    phone: null,
    website: null,
    weekdayHours: ["Monday: Open 24 hours"],
    reviews: [{ text: "24-hour access, power racks and a small pool.", rating: 5 }],
    editorialSummary: "Premium 24-hour gym focused on strength training.",
    distanceKm: null,
    score: 0,
    labels: [],
    isDemo: true,
  },
  {
    id: "demo-kilimani",
    name: "Kilimani Yoga & Conditioning",
    address: "Argwings Kodhek Road, Kilimani",
    location: { lat: -1.2921, lng: 36.787 },
    rating: 4.4,
    userRatingCount: 89,
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    openNow: false,
    types: ["gym", "yoga_studio"],
    photoName: null,
    googleMapsUri: "https://www.google.com/maps/search/?api=1&query=yoga%20Kilimani%20Nairobi",
    phone: null,
    website: null,
    weekdayHours: ["Monday: 6:00 AM – 8:00 PM"],
    reviews: [{ text: "Affordable yoga, pilates and light cardio.", rating: 4 }],
    editorialSummary: "Budget-friendly studio for flexibility and conditioning.",
    distanceKm: null,
    score: 0,
    labels: [],
    isDemo: true,
  },
  {
    id: "demo-mombasa",
    name: "Nyali Athletic Club",
    address: "Links Road, Nyali, Mombasa",
    location: { lat: -4.043, lng: 39.706 },
    rating: 4.5,
    userRatingCount: 131,
    priceLevel: "PRICE_LEVEL_MODERATE",
    openNow: true,
    types: ["gym", "sports_complex"],
    photoName: null,
    googleMapsUri: "https://www.google.com/maps/search/?api=1&query=gym%20Nyali%20Mombasa",
    phone: null,
    website: null,
    weekdayHours: ["Monday: 5:30 AM – 9:00 PM"],
    reviews: [{ text: "Cardio machines, weights and a swimming pool.", rating: 5 }],
    editorialSummary: "Coast gym with pool, sports courts and group classes.",
    distanceKm: null,
    score: 0,
    labels: [],
    isDemo: true,
  },
  {
    id: "demo-kisumu",
    name: "Kisumu Iron Works",
    address: "Oginga Odinga Street, Kisumu",
    location: { lat: -0.1022, lng: 34.7617 },
    rating: 4.2,
    userRatingCount: 76,
    priceLevel: "PRICE_LEVEL_INEXPENSIVE",
    openNow: true,
    types: ["gym"],
    photoName: null,
    googleMapsUri: "https://www.google.com/maps/search/?api=1&query=gym%20Kisumu",
    phone: null,
    website: null,
    weekdayHours: ["Monday: 5:00 AM – 9:00 PM"],
    reviews: [{ text: "Solid free weights and boxing classes.", rating: 4 }],
    editorialSummary: "No-frills strength gym in Kisumu CBD.",
    distanceKm: null,
    score: 0,
    labels: [],
    isDemo: true,
  },
];
